name: DocHub Server CI/CD
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v4

      - name: Setup AWS ECR Details
        uses: aws-actions/configure-aws-credentials@v4.0.1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{secrets.AWS_REGION}}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2.0.1

      - name: Build docker image
        env:
          ECR_REPOSITORY: ${{secrets.AWS_ECR_REPO}}
          ECR_REGISTRY: 463226896905.dkr.ecr.ap-south-1.amazonaws.com
          IMAGE_TAG: ${{github.run_number}}
        run: |
          echo $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          docker build -t 463226896905.dkr.ecr.ap-south-1.amazonaws.com/dochub:$IMAGE_TAG .

      - name: Push to ECR
        env:
          ECR_REGISTRY: 463226896905.dkr.ecr.ap-south-1.amazonaws.com
          ECR_REPOSITORY: ${{secrets.AWS_ECR_REPO}}
          IMAGE_TAG: ${{github.run_number}}
        run: docker push 463226896905.dkr.ecr.ap-south-1.amazonaws.com/dochub:$IMAGE_TAG
